/*
 * Project Aegis - ZKP Verification Module (v5.0 - Real Math)
 *
 * Verifies a Zero Knowledge Proof generated by zkp_prover.
 * Privacy Guarantee: The Verifier NEVER sees the private inputs (e.g. Birth Year).
 * It only checks if Proof(Public, Private) corresponds to Public Constraints.
 */

#include "zkp_circuits.hpp"
#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
    // Usage: zkp_verifier <proof_hex_string> <current_year> <threshold> <vk_path>
    if (argc != 5) {
        std::cerr << "Usage: " << argv[0] << " <proof_string> <current_year> <threshold> <vk_path>" << std::endl;
        return 1;
    }

    try {
        ZkpManager::init();
    } catch (const std::exception& e) {
        std::cerr << "FATAL: Crypto Init Failed: " << e.what() << std::endl;
        return 1;
    }

    std::string proof_str = argv[1];
    long current_year = std::stol(argv[2]);
    long threshold = std::stol(argv[3]);
    std::string vk_path = argv[4];

    try {
        // 1. Load Verification Key
        // In a real server, this would be pre-loaded, not loaded per request.
        auto vk = ZkpManager::load_vk(vk_path);

        // 2. Mathematically Verify
        bool valid = ZkpManager::verify_proof(vk, proof_str, current_year, threshold);

        if (valid) {
            std::cout << "VERIFICATION_SUCCESS" << std::endl;
            return 0;
        } else {
            std::cout << "VERIFICATION_FAILURE" << std::endl;
            return 2;
        }

    } catch (const std::exception& e) {
        std::cerr << "Error during verification: " << e.what() << std::endl;
        return 2;
    }
}
